sudo apt install nala -y
sudo nala install -y hwdata libliftoff-dev libwlroots-dev build-essential  cmake cmake-extras curl gettext gir1.2-graphene-1.0 git glslang-tools gobject-introspection golang hwdata jq libavcodec-dev libavformat-dev libavutil-dev libcairo2-dev libdeflate-dev libdisplay-info-dev libdrm-dev libegl1-mesa-dev libgbm-dev libgdk-pixbuf-2.0-dev libgdk-pixbuf2.0-bin libgirepository1.0-dev libgl1-mesa-dev libgraphene-1.0-0 libgraphene-1.0-dev libgtk-3-dev libgulkan-0.15-0 libgulkan-dev libinih-dev libinput-dev libjbig-dev libjpeg-dev libjpeg62-turbo-dev liblerc-dev libliftoff-dev liblzma-dev libnotify-bin libpam0g-dev libpango1.0-dev libpipewire-0.3-dev libqt6svg6 libseat-dev libstartup-notification0-dev libswresample-dev libsystemd-dev libtiff-dev libtiffxx6 libtomlplusplus-dev libudev-dev libvkfft-dev libvulkan-dev libvulkan-volk-dev libwayland-dev libwebp-dev libxcb-composite0-dev libxcb-cursor-dev libxcb-dri3-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-present-dev libxcb-render-util0-dev libxcb-res0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xinput-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libxkbregistry-dev libxml2-dev libxxhash-dev meson ninja-build openssl psmisc python3-mako python3-markdown python3-markupsafe python3-yaml qt6-base-dev scdoc seatd spirv-tools vulkan-utility-libraries-dev wayland-protocols xdg-desktop-portal xwayland  git  liblz4-dev fish libxcb-util-dev libxcb-util0-dev libxcb-util1 libxcb-cursor-dev libxcb-cursor0 libxcb-xinerama0 libstartup-notification0-dev xwayland meson git wget  build-essential ninja-build cmake-extras cmake gettext gettext-base fontconfig libfontconfig-dev libffi-dev libxml2-dev libdrm-dev libxkbcommon-x11-dev libxkbregistry-dev libxkbcommon-dev libpixman-1-dev libudev-dev libseat-dev seatd libxcb-dri3-dev libvulkan-dev libvulkan-volk-dev libvkfft-dev libgulkan-dev libegl-dev libgles2 libegl1-mesa-dev glslang-tools libinput-bin libinput-dev libxcb-composite0-dev libavutil-dev libavcodec-dev libavformat-dev libxcb-ewmh2 libxcb-ewmh-dev libxcb-present-dev libxcb-icccm4-dev libxcb-render-util0-dev libxcb-res0-dev libxcb-xinput-dev libpango1.0-dev xdg-desktop-portal-wlr libzip-dev libcairo2-dev librsvg2-dev wl-clipboard slurp grim sxiv mpv sway-notification-center


xdg-user-dirs-update
mkdir ~/Screenshots/

# Thunar
sudo nala install -y thunar thunar-archive-plugin thunar-volman file-roller

